services:
  postgresql:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    image: postgres:15.3-alpine
    ports:
      - "15433:5432"
    volumes:
      - "postgresql-db:/var/lib/postgresql/data"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3005 -b '0.0.0.0'"
    depends_on:
      - postgresql
    environment:
      DATABASE_PASSWORD: password
    ports:
      - "3005:3005"
    volumes:
      - ./web:/web
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - ./front:/front
    tty: true
    # https://github.com/vitejs/vite/discussions/3396
    command: sh -c "npm install && npm run dev -- --host"
volumes:
  postgresql-db:
